FROM rust:1.71-alpine AS builder

WORKDIR /app
COPY . .
RUN set -xe ;\
  apk add --no-cache musl-dev ;\
  cargo install --path .


FROM alpine
COPY --from=builder /usr/local/cargo/bin/shortener /usr/local/bin/shortener
COPY --from=builder /app/Rocket-compose.toml /app/Rocket.toml
ENV ROCKET_CONFIG=/app/Rocket.toml
CMD ["shortener"]
