name: Shortener build
on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"

jobs:

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
